/**
 * Generate main list page (without dialogs)
 */

import { ModelInfo } from '../../introspect';
import { toCamelCase, toPascalCase, pluralize, toKebabCase } from '../../utils';

export function generateMainPage(model: ModelInfo): string {
  const modelName = toPascalCase(model.name);
  const modelNameLower = toCamelCase(model.name);
  const modelNameKebab = toKebabCase(model.name);
  const modelPlural = pluralize(modelNameLower);
  const modelPluralPascal = toPascalCase(modelPlural);
  const modelPluralDisplay = toPascalCase(pluralize(model.name));

  return `/**
 * ${modelName} main page
 * Generated by CRUD generator
 */

import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Plus } from "lucide-react";
import { ${modelName}List } from "./_components/${modelNameKebab}-list";

// Mock server function - replace with actual implementation
async function get${modelPluralPascal}() {
  // TODO: Implement actual server function in lib/server/${modelPlural}.ts
  // Mock data for UI preview
  const mock${modelPluralPascal} = [
    // Add mock data here
  ];

  return mock${modelPluralPascal};
}

export default async function ${modelName}Page() {
  const ${modelPlural} = await get${modelPluralPascal}();

  return (
    <div className="container mx-auto py-10">
      <div className="flex justify-between items-center mb-6">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">${modelPluralDisplay}</h1>
          <p className="text-muted-foreground">
            Manage your ${modelPlural.toLowerCase()}
          </p>
        </div>
        <Link href="/${modelPlural}/create">
          <Button>
            <Plus className="mr-2 h-4 w-4" />
            Add ${modelName}
          </Button>
        </Link>
      </div>

      <${modelName}List ${modelPlural}={${modelPlural}} />
    </div>
  );
}
`;
}
