/**
 * Generate API client functions
 */

import { ModelInfo } from '../introspect';
import { toCamelCase, toPascalCase, pluralize } from '../utils';

export function generateApiClient(model: ModelInfo): string {
  const modelName = toPascalCase(model.name);
  const modelNameLower = toCamelCase(model.name);
  const modelPlural = pluralize(modelNameLower);
  const modelPluralPascal = toPascalCase(modelPlural);

  return `/**
 * ${modelName} API client functions
 * Generated by CRUD generator
 */

import type {
  ${modelName},
  ${modelName}ApiData,
  PaginatedResponse,
} from "@/${modelPlural}/_types";

export class ValidationError extends Error {
  constructor(
    message: string,
    public errors: Record<string, string[]>
  ) {
    super(message);
    this.name = "ValidationError";
  }
}

interface FetchOptions {
  page?: number;
  pageSize?: number;
  search?: string;
  status?: string;
}

/**
 * Fetch paginated ${modelPlural}
 */
export async function fetch${modelPluralPascal}(
  options: FetchOptions = {}
): Promise<PaginatedResponse<${modelName}>> {
  const { page = 1, pageSize = 10, search = "", status = "" } = options;

  const params = new URLSearchParams({
    page: page.toString(),
    pageSize: pageSize.toString(),
    ...(search && { search }),
    ...(status && { status }),
  });

  const response = await fetch(\`/api/${modelPlural}?\${params}\`);

  if (!response.ok) {
    throw new Error("Failed to fetch ${modelPlural}");
  }

  return response.json();
}

/**
 * Fetch a single ${modelNameLower} by ID
 */
export async function fetch${modelName}ById(id: string): Promise<${modelName}> {
  const response = await fetch(\`/api/${modelPlural}?id=\${id}\`);

  if (!response.ok) {
    throw new Error("Failed to fetch ${modelNameLower}");
  }

  const data = await response.json();
  return data.data;
}

/**
 * Get a single ${modelNameLower} by ID (alias for server components)
 */
export async function get${modelName}ById(id: string): Promise<${modelName} | null> {
  try {
    return await fetch${modelName}ById(id);
  } catch (error) {
    console.error('Error fetching ${modelNameLower}:', error);
    return null;
  }
}

/**
 * Create a new ${modelNameLower}
 */
export async function create${modelName}(
  data: ${modelName}ApiData
): Promise<${modelName}> {
  const response = await fetch("/api/${modelPlural}", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify(data),
  });

  if (!response.ok) {
    const errorData = await response.json();
    if (response.status === 400 && errorData.errors) {
      throw new ValidationError(errorData.message, errorData.errors);
    }
    throw new Error(errorData.message || "Failed to create ${modelNameLower}");
  }

  return response.json();
}

/**
 * Update an existing ${modelNameLower}
 */
export async function update${modelName}(
  id: string,
  data: ${modelName}ApiData
): Promise<${modelName}> {
  const response = await fetch(\`/api/${modelPlural}?id=\${id}\`, {
    method: "PUT",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify(data),
  });

  if (!response.ok) {
    const errorData = await response.json();
    if (response.status === 400 && errorData.errors) {
      throw new ValidationError(errorData.message, errorData.errors);
    }
    throw new Error(errorData.message || "Failed to update ${modelNameLower}");
  }

  return response.json();
}

/**
 * Delete a ${modelNameLower}
 */
export async function delete${modelName}(id: string): Promise<void> {
  const response = await fetch(\`/api/${modelPlural}?id=\${id}\`, {
    method: "DELETE",
  });

  if (!response.ok) {
    const errorData = await response.json();
    throw new Error(errorData.message || "Failed to delete ${modelNameLower}");
  }
}
`;
}
