/**
 * Generate page.tsx (Server Component)
 */

import { ModelInfo } from '../introspect';
import { toCamelCase, toPascalCase, pluralize } from '../utils';

export function generatePage(model: ModelInfo): string {
  const modelName = toPascalCase(model.name);
  const modelNameLower = toCamelCase(model.name);
  const modelPlural = pluralize(modelNameLower);
  const modelPluralPascal = toPascalCase(modelPlural);

  return `/**
 * ${modelName} page
 * Generated by CRUD generator
 */

import { ${modelName}ClientPage } from "./_components/${modelNameLower}-client-page";

// Mock server function - replace with actual implementation
async function get${modelPluralPascal}(options: {
  page: number;
  pageSize: number;
  search?: string;
  status?: string;
}) {
  // TODO: Implement actual server function in lib/server/${modelPlural}.ts
  // For now, return empty data
  return {
    data: [],
    metadata: {
      page: options.page,
      pageSize: options.pageSize,
      total: 0,
      totalPages: 0,
    },
  };
}

interface PageProps {
  searchParams: Promise<{
    page?: string;
    search?: string;
    status?: string;
  }>;
}

export default async function ${modelName}Page({ searchParams }: PageProps) {
  const params = await searchParams;
  const page = Number(params.page) || 1;
  const search = params.search || "";
  const status = params.status || "";

  const data = await get${modelPluralPascal}({
    page,
    pageSize: 10,
    search,
    status,
  });

  return <${modelName}ClientPage initialData={data} />;
}
`;
}
