/**
 * Generate TypeScript type definitions
 */

import { ModelInfo, FieldInfo } from '../introspect';
import { getTypeScriptType, toPascalCase } from '../utils';

export function generateTypes(model: ModelInfo): string {
  const modelName = toPascalCase(model.name);

  // Generate base type
  const typeFields = model.fields
    .map((field) => {
      const tsType = field.isEnum
        ? field.enumValues!.map((v) => `"${v}"`).join(' | ')
        : getTypeScriptType(field.type, field.isOptional);

      return `  ${field.name}: ${tsType};`;
    })
    .join('\n');

  // Generate form type (status as boolean if enum exists)
  const formFields = model.fields
    .filter((f) => !f.isPrimaryKey)
    .map((field) => {
      let tsType: string;

      if (field.name === 'status' && field.isEnum) {
        tsType = 'boolean';
      } else if (field.isEnum) {
        tsType = field.enumValues!.map((v) => `"${v}"`).join(' | ');
      } else {
        tsType = getTypeScriptType(field.type, field.isOptional);
      }

      return `  ${field.name}: ${tsType};`;
    })
    .join('\n');

  // Generate API type (status as enum)
  const apiFields = model.fields
    .filter((f) => !f.isPrimaryKey)
    .map((field) => {
      const tsType = field.isEnum
        ? field.enumValues!.map((v) => `"${v}"`).join(' | ')
        : getTypeScriptType(field.type, field.isOptional);

      return `  ${field.name}: ${tsType};`;
    })
    .join('\n');

  // Find status enum values if exists
  const statusField = model.fields.find((f) => f.name === 'status' && f.isEnum);
  const statusEnum = statusField
    ? `\nexport type ${modelName}Status = ${statusField.enumValues!.map((v) => `"${v}"`).join(' | ')};\n`
    : '';

  return `/**
 * ${modelName} type definitions
 * Generated by CRUD generator
 */

export interface ${modelName} {
${typeFields}
}

export interface ${modelName}FormData {
${formFields}
}

export interface ${modelName}ApiData {
${apiFields}
}
${statusEnum}
export interface PaginatedResponse<T> {
  data: T[];
  metadata: {
    page: number;
    pageSize: number;
    total: number;
    totalPages: number;
  };
}
`;
}
