/**
 * Generate Zod validation schemas
 */

import { ModelInfo, FieldInfo } from '../introspect';
import { toCamelCase, toPascalCase } from '../utils';

export function generateValidations(model: ModelInfo): string {
  const modelName = toPascalCase(model.name);
  const modelNameLower = toCamelCase(model.name);

  // Generate form schema (boolean for status)
  const formSchemaFields = model.fields
    .filter((f) => !f.isPrimaryKey)
    .map((field) => {
      let validation = '';

      if (field.name === 'status' && field.isEnum) {
        // Status as boolean in form
        validation = `  ${field.name}: z.boolean()`;
      } else if (field.isEnum) {
        // Regular enum
        const enumValues = field.enumValues!.map((v) => `"${v}"`).join(', ');
        validation = `  ${field.name}: z.enum([${enumValues}])`;
      } else {
        // Regular field
        validation = `  ${field.name}: ${getZodValidation(field)}`;
      }

      return validation + ',';
    })
    .join('\n');

  // Generate API schema (enum for status)
  const apiSchemaFields = model.fields
    .filter((f) => !f.isPrimaryKey)
    .map((field) => {
      let validation = '';

      if (field.isEnum) {
        const enumValues = field.enumValues!.map((v) => `"${v}"`).join(', ');
        validation = `  ${field.name}: z.enum([${enumValues}])`;
      } else {
        validation = `  ${field.name}: ${getZodValidation(field)}`;
      }

      return validation + ',';
    })
    .join('\n');

  return `/**
 * ${modelName} validation schemas
 * Generated by CRUD generator
 */

import { z } from "zod";

/**
 * Form validation schema (status as boolean)
 */
export const ${modelNameLower}Schema = z.object({
${formSchemaFields}
});

/**
 * API validation schema (status as enum)
 */
export const ${modelNameLower}ApiSchema = z.object({
${apiSchemaFields}
});

export type ${modelName}FormInput = z.infer<typeof ${modelNameLower}Schema>;
export type ${modelName}ApiInput = z.infer<typeof ${modelNameLower}ApiSchema>;
`;
}

function getZodValidation(field: FieldInfo): string {
  let validation = '';

  switch (field.type) {
    case 'String':
      validation = 'z.string()';
      if (!field.isOptional) {
        validation += `.min(1, "${getFieldLabel(field.name)} is required")`;
      }
      // Add max length for common fields
      if (field.name.includes('name')) {
        validation += '.max(255)';
      }
      if (field.name.includes('email')) {
        validation += '.email("Invalid email address")';
      }
      if (field.name.includes('phone')) {
        validation += '.regex(/^[0-9+\\-\\s()]*$/, "Invalid phone number")';
      }
      break;

    case 'Int':
      validation = 'z.number().int()';
      if (!field.isOptional) {
        validation += `.min(0, "${getFieldLabel(field.name)} must be non-negative")`;
      }
      break;

    case 'Decimal':
      validation = 'z.number()';
      if (!field.isOptional) {
        validation += `.min(0, "${getFieldLabel(field.name)} must be non-negative")`;
      }
      if (field.name.includes('price')) {
        validation += '.multipleOf(0.01)';
      }
      break;

    case 'Boolean':
      validation = 'z.boolean()';
      break;

    case 'DateTime':
      validation = 'z.date()';
      break;

    default:
      validation = 'z.string()';
  }

  if (field.isOptional) {
    validation += '.optional()';
  }

  return validation;
}

function getFieldLabel(fieldName: string): string {
  return fieldName
    .replace(/_/g, ' ')
    .replace(/([A-Z])/g, ' $1')
    .trim()
    .split(' ')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}
