/**
 * Generate client page component
 */

import { ModelInfo } from '../../introspect';
import { toCamelCase, toPascalCase, pluralize, getDisplayLabel } from '../../utils';

export function generateClientPageComponent(model: ModelInfo): string {
  const modelName = toPascalCase(model.name);
  const modelNameLower = toCamelCase(model.name);
  const modelPlural = pluralize(modelNameLower);
  const modelPluralPascal = toPascalCase(modelPlural);
  const modelPluralDisplay = pluralize(getDisplayLabel(model.name));

  // Check if has status field
  const hasStatus = model.fields.some((f) => f.name === 'status' && f.isEnum);
  const statusField = model.fields.find((f) => f.name === 'status' && f.isEnum);

  return `/**
 * ${modelName} client page component
 * Generated by CRUD generator
 */

"use client";

import { useState, useEffect } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";${hasStatus ? `
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";` : ''}
import { Plus, Search } from "lucide-react";
import { toast } from "sonner";
import { ${modelName}List } from "./${modelNameLower}-list";
import { ${modelName}FormDialog } from "./${modelNameLower}-form-dialog";
import { useDebounce } from "@/hooks/useDebounce";
import {
  fetch${modelPluralPascal},
  delete${modelName},
} from "@/${modelPlural}/_lib/api-client";
import type { ${modelName}, PaginatedResponse } from "@/${modelPlural}/_types";

interface ${modelName}ClientPageProps {
  initialData: PaginatedResponse<${modelName}>;
}

export function ${modelName}ClientPage({ initialData }: ${modelName}ClientPageProps) {
  const router = useRouter();
  const searchParams = useSearchParams();

  const [data, setData] = useState<PaginatedResponse<${modelName}>>(initialData);
  const [search, setSearch] = useState(searchParams.get("search") || "");${hasStatus ? `
  const [statusFilter, setStatusFilter] = useState(
    searchParams.get("status") || ""
  );` : ''}
  const [currentPage, setCurrentPage] = useState(
    Number(searchParams.get("page")) || 1
  );
  const [isLoading, setIsLoading] = useState(false);
  const [dialogOpen, setDialogOpen] = useState(false);
  const [editing${modelName}, setEditing${modelName}] = useState<${modelName} | undefined>();

  const debouncedSearch = useDebounce(search, 500);

  // Fetch data when filters change
  useEffect(() => {
    const fetchData = async () => {
      setIsLoading(true);
      try {
        const result = await fetch${modelPluralPascal}({
          page: currentPage,
          pageSize: 10,
          search: debouncedSearch,${hasStatus ? `
          status: statusFilter,` : ''}
        });
        setData(result);

        // Update URL
        const urlParams = new URLSearchParams();
        if (debouncedSearch) urlParams.set("search", debouncedSearch);${hasStatus ? `
        if (statusFilter) urlParams.set("status", statusFilter);` : ''}
        if (currentPage > 1) urlParams.set("page", currentPage.toString());

        router.replace(\`?\${urlParams.toString()}\`, { scroll: false });
      } catch (error) {
        toast.error("Failed to fetch ${modelPlural}");
        console.error(error);
      } finally {
        setIsLoading(false);
      }
    };

    fetchData();
  }, [debouncedSearch,${hasStatus ? ' statusFilter,' : ''} currentPage, router]);

  const handleEdit = (${modelNameLower}: ${modelName}) => {
    setEditing${modelName}(${modelNameLower});
    setDialogOpen(true);
  };

  const handleDelete = async (id: string) => {
    try {
      await delete${modelName}(id);
      toast.success("${modelName} deleted successfully");

      // Refetch data
      const result = await fetch${modelPluralPascal}({
        page: currentPage,
        pageSize: 10,
        search: debouncedSearch,${hasStatus ? `
        status: statusFilter,` : ''}
      });
      setData(result);
    } catch (error) {
      toast.error("Failed to delete ${modelNameLower}");
      console.error(error);
    }
  };

  const handleSuccess = async () => {
    setEditing${modelName}(undefined);

    // Refetch data
    const result = await fetch${modelPluralPascal}({
      page: currentPage,
      pageSize: 10,
      search: debouncedSearch,${hasStatus ? `
      status: statusFilter,` : ''}
    });
    setData(result);
  };

  const handleDialogClose = (open: boolean) => {
    setDialogOpen(open);
    if (!open) {
      setEditing${modelName}(undefined);
    }
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">${modelPluralDisplay}</h1>
          <p className="text-muted-foreground">
            Manage your ${modelPlural.toLowerCase()}
          </p>
        </div>
        <Button onClick={() => setDialogOpen(true)}>
          <Plus className="mr-2 h-4 w-4" />
          Add ${modelName}
        </Button>
      </div>

      {/* Filters */}
      <div className="flex gap-4">
        <div className="relative flex-1">
          <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
          <Input
            placeholder="Search ${modelPlural.toLowerCase()}..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="pl-10"
          />
        </div>${hasStatus ? `
        <Select value={statusFilter} onValueChange={setStatusFilter}>
          <SelectTrigger className="w-[180px]">
            <SelectValue placeholder="All Status" />
          </SelectTrigger>
          <SelectContent>${statusField!.enumValues!.map(val => `
            <SelectItem value="${val}">${val}</SelectItem>`).join('')}
          </SelectContent>
        </Select>` : ''}
      </div>

      {/* List */}
      {isLoading ? (
        <div className="flex items-center justify-center py-12">
          <p className="text-muted-foreground">Loading...</p>
        </div>
      ) : (
        <>
          <${modelName}List
            ${modelPlural}={data.data}
            onEdit={handleEdit}
            onDelete={handleDelete}
          />

          {/* Pagination */}
          {data.metadata.totalPages > 1 && (
            <div className="flex items-center justify-between">
              <p className="text-sm text-muted-foreground">
                Showing {(currentPage - 1) * data.metadata.pageSize + 1} to{" "}
                {Math.min(
                  currentPage * data.metadata.pageSize,
                  data.metadata.total
                )}{" "}
                of {data.metadata.total} results
              </p>
              <div className="flex gap-2">
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => setCurrentPage((p) => Math.max(1, p - 1))}
                  disabled={currentPage === 1}
                >
                  Previous
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() =>
                    setCurrentPage((p) =>
                      Math.min(data.metadata.totalPages, p + 1)
                    )
                  }
                  disabled={currentPage === data.metadata.totalPages}
                >
                  Next
                </Button>
              </div>
            </div>
          )}
        </>
      )}

      {/* Form Dialog */}
      <${modelName}FormDialog
        open={dialogOpen}
        onOpenChange={handleDialogClose}
        ${modelNameLower}={editing${modelName}}
        onSuccess={handleSuccess}
      />
    </div>
  );
}
`;
}
