/**
 * Generate form dialog component
 */

import { ModelInfo } from '../../introspect';
import { toCamelCase, toPascalCase, pluralize } from '../../utils';

export function generateFormDialogComponent(model: ModelInfo): string {
  const modelName = toPascalCase(model.name);
  const modelNameLower = toCamelCase(model.name);
  const modelPlural = pluralize(modelNameLower);

  // Get status field if exists
  const statusField = model.fields.find((f) => f.name === 'status' && f.isEnum);
  const hasStatus = !!statusField;

  return `/**
 * ${modelName} form dialog component
 * Generated by CRUD generator
 */

"use client";

import { useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { toast } from "sonner";
import { ${modelName}Form } from "./${modelNameLower}-form";
import {
  create${modelName},
  update${modelName},
  ValidationError,
} from "@/${modelPlural}/_lib/api-client";
import type { ${modelName}FormData } from "@/${modelPlural}/_types";
import type { ${modelName} } from "@/${modelPlural}/_types";

interface ${modelName}FormDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  ${modelNameLower}?: ${modelName};
  onSuccess: () => void;
}

export function ${modelName}FormDialog({
  open,
  onOpenChange,
  ${modelNameLower},
  onSuccess,
}: ${modelName}FormDialogProps) {
  const [isSubmitting, setIsSubmitting] = useState(false);

  const handleSubmit = async (data: ${modelName}FormData) => {
    setIsSubmitting(true);

    try {
      // Transform form data to API format${hasStatus ? `
      const apiData = {
        ...data,
        status: data.status ? "${statusField!.enumValues![0]}" : "${statusField!.enumValues![statusField!.enumValues!.length - 1]}",
      };` : `
      const apiData = data;`}

      if (${modelNameLower}) {
        await update${modelName}(${modelNameLower}.id, apiData as any);
        toast.success("${modelName} updated successfully");
      } else {
        await create${modelName}(apiData as any);
        toast.success("${modelName} created successfully");
      }

      onOpenChange(false);
      onSuccess();
    } catch (error) {
      if (error instanceof ValidationError) {
        toast.error(error.message);
      } else {
        toast.error(
          ${modelNameLower}
            ? "Failed to update ${modelNameLower}"
            : "Failed to create ${modelNameLower}"
        );
      }
      console.error(error);
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>
            {${modelNameLower} ? "Edit ${modelName}" : "Create ${modelName}"}
          </DialogTitle>
        </DialogHeader>
        <${modelName}Form
          ${modelNameLower}={${modelNameLower}}
          onSubmit={handleSubmit}
          onCancel={() => onOpenChange(false)}
          isSubmitting={isSubmitting}
        />
      </DialogContent>
    </Dialog>
  );
}
`;
}
