/**
 * Generate form component
 */

import { ModelInfo, FieldInfo } from '../../introspect';
import { toCamelCase, toPascalCase, pluralize, getDisplayLabel } from '../../utils';

export function generateFormComponent(model: ModelInfo): string {
  const modelName = toPascalCase(model.name);
  const modelNameLower = toCamelCase(model.name);
  const modelPlural = pluralize(modelNameLower);

  // Generate form fields
  const formFields = model.fields
    .filter((f) => !f.isPrimaryKey)
    .map((field) => generateFormField(field, modelNameLower))
    .join('\n\n');

  // Check if we need Switch component
  const hasSwitch = model.fields.some(
    (f) => f.type === 'Boolean' || (f.name === 'status' && f.isEnum)
  );

  // Check if we need Select component
  const hasSelect = model.fields.some((f) => f.isEnum && f.name !== 'status');

  return `/**
 * ${modelName} form component
 * Generated by CRUD generator
 */

"use client";

import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";${hasSwitch ? '\nimport { Switch } from "@/components/ui/switch";' : ''}${hasSelect ? '\nimport { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";' : ''}
import { ${modelNameLower}Schema } from "@/${modelPlural}/_validations/${modelNameLower}";
import type { ${modelName}FormData } from "@/${modelPlural}/_types";
import type { ${modelName} } from "@/${modelPlural}/_types";

interface ${modelName}FormProps {
  ${modelNameLower}?: ${modelName};
  onSubmit: (data: ${modelName}FormData) => void;
  onCancel: () => void;
  isSubmitting?: boolean;
}

export function ${modelName}Form({
  ${modelNameLower},
  onSubmit,
  onCancel,
  isSubmitting = false,
}: ${modelName}FormProps) {
  const {
    register,
    handleSubmit,
    setValue,
    watch,
    formState: { errors },
  } = useForm<${modelName}FormData>({
    resolver: zodResolver(${modelNameLower}Schema),
    defaultValues: ${modelNameLower}
      ? {
${generateDefaultValues(model)}
        }
      : undefined,
  });

  return (
    <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
${formFields}

      <div className="flex justify-end gap-2 pt-4">
        <Button
          type="button"
          variant="outline"
          onClick={onCancel}
          disabled={isSubmitting}
        >
          Cancel
        </Button>
        <Button type="submit" disabled={isSubmitting}>
          {isSubmitting ? "Saving..." : "Save"}
        </Button>
      </div>
    </form>
  );
}
`;
}

function generateFormField(field: FieldInfo, modelNameLower: string): string {
  const label = getDisplayLabel(field.name);
  const fieldName = field.name;

  // Special handling for status field with enum
  if (fieldName === 'status' && field.isEnum) {
    const activeValue = field.enumValues!.find(v => v.toUpperCase() === 'ACTIVE') || field.enumValues![0];
    const inactiveValue = field.enumValues!.find(v => v.toUpperCase() === 'INACTIVE') || field.enumValues![field.enumValues!.length - 1];

    return `      <div className="space-y-2">
        <div className="flex items-center justify-between">
          <Label htmlFor="${fieldName}">${label}</Label>
          <Switch
            id="${fieldName}"
            checked={watch("${fieldName}")}
            onCheckedChange={(checked) => setValue("${fieldName}", checked)}
          />
        </div>
        <p className="text-sm text-muted-foreground">
          {watch("${fieldName}") ? "${activeValue}" : "${inactiveValue}"}
        </p>
      </div>`;
  }

  // Boolean field
  if (field.type === 'Boolean') {
    return `      <div className="flex items-center justify-between">
        <Label htmlFor="${fieldName}">${label}</Label>
        <Switch
          id="${fieldName}"
          checked={watch("${fieldName}")}
          onCheckedChange={(checked) => setValue("${fieldName}", checked)}
        />
      </div>`;
  }

  // Enum field (not status)
  if (field.isEnum) {
    const options = field.enumValues!.map(
      (val) => `            <SelectItem value="${val}">${val}</SelectItem>`
    ).join('\n');

    return `      <div className="space-y-2">
        <Label htmlFor="${fieldName}">${label}</Label>
        <Select
          value={watch("${fieldName}")}
          onValueChange={(value) => setValue("${fieldName}", value as any)}
        >
          <SelectTrigger id="${fieldName}">
            <SelectValue placeholder="Select ${label.toLowerCase()}" />
          </SelectTrigger>
          <SelectContent>
${options}
          </SelectContent>
        </Select>
        {errors.${fieldName} && (
          <p className="text-sm text-destructive">{errors.${fieldName}?.message}</p>
        )}
      </div>`;
  }

  // DateTime field
  if (field.type === 'DateTime') {
    return `      <div className="space-y-2">
        <Label htmlFor="${fieldName}">${label}</Label>
        <Input
          id="${fieldName}"
          type="date"
          {...register("${fieldName}", { valueAsDate: true })}
        />
        {errors.${fieldName} && (
          <p className="text-sm text-destructive">{errors.${fieldName}?.message}</p>
        )}
      </div>`;
  }

  // Number field
  if (field.type === 'Int' || field.type === 'Decimal') {
    const step = field.type === 'Decimal' ? '0.01' : '1';
    return `      <div className="space-y-2">
        <Label htmlFor="${fieldName}">${label}</Label>
        <Input
          id="${fieldName}"
          type="number"
          step="${step}"
          {...register("${fieldName}", { valueAsNumber: true })}
        />
        {errors.${fieldName} && (
          <p className="text-sm text-destructive">{errors.${fieldName}?.message}</p>
        )}
      </div>`;
  }

  // String field (default)
  return `      <div className="space-y-2">
        <Label htmlFor="${fieldName}">${label}</Label>
        <Input
          id="${fieldName}"
          {...register("${fieldName}")}
          placeholder="Enter ${label.toLowerCase()}"
        />
        {errors.${fieldName} && (
          <p className="text-sm text-destructive">{errors.${fieldName}?.message}</p>
        )}
      </div>`;
}

function generateDefaultValues(model: ModelInfo): string {
  return model.fields
    .filter((f) => !f.isPrimaryKey)
    .map((field) => {
      if (field.name === 'status' && field.isEnum) {
        // Status as boolean - check if current value matches "ACTIVE" or first enum value
        const activeValue = field.enumValues!.find(v => v.toUpperCase() === 'ACTIVE') || field.enumValues![0];
        return `          ${field.name}: ${model.name}.${field.name} === "${activeValue}",`;
      }
      return `          ${field.name}: ${model.name}.${field.name},`;
    })
    .join('\n');
}
