/**
 * Generate list component for page-based navigation (with edit links)
 */

import { ModelInfo, FieldInfo } from '../../introspect';
import { toCamelCase, toPascalCase, pluralize, getDisplayLabel } from '../../utils';

export function generatePageBasedListComponent(model: ModelInfo): string {
  const modelName = toPascalCase(model.name);
  const modelNameLower = toCamelCase(model.name);
  const modelPlural = pluralize(modelNameLower);

  // Get display fields (exclude timestamps, limit to first 5 fields)
  const displayFields = model.fields
    .filter((f) => !['created_at', 'updated_at', 'createdBy', 'updatedBy', 'created_by', 'updated_by'].includes(f.name))
    .slice(0, 5);

  // Generate table headers
  const tableHeaders = displayFields
    .map((field) => `        <TableHead>${getDisplayLabel(field.name)}</TableHead>`)
    .join('\n');

  // Generate table cells
  const tableCells = displayFields
    .map((field) => generateTableCell(field, modelNameLower))
    .join('\n');

  return `/**
 * ${modelName} list component
 * Generated by CRUD generator
 */

"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { MoreHorizontal, Pencil, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { delete${modelName} } from "@/${modelPlural}/_lib/api-client";
import type { ${modelName} } from "@/${modelPlural}/_types";

interface ${modelName}ListProps {
  ${modelPlural}: ${modelName}[];
}

export function ${modelName}List({ ${modelPlural} }: ${modelName}ListProps) {
  const router = useRouter();
  const [deletingId, setDeletingId] = useState<string | null>(null);

  const handleEdit = (id: string) => {
    router.push(\`/${modelPlural}/\${id}/edit\`);
  };

  const handleDelete = async (id: string) => {
    if (confirm("Are you sure you want to delete this ${modelNameLower}?")) {
      setDeletingId(id);
      try {
        await delete${modelName}(id);
        toast.success("${modelName} deleted successfully");
        router.refresh();
      } catch (error) {
        toast.error("Failed to delete ${modelNameLower}");
        console.error(error);
      } finally {
        setDeletingId(null);
      }
    }
  };

  if (${modelPlural}.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center py-12 text-center">
        <p className="text-muted-foreground">No ${modelPlural} found</p>
      </div>
    );
  }

  return (
    <div className="rounded-md border">
      <Table>
        <TableHeader>
          <TableRow>
${tableHeaders}
            <TableHead className="w-[70px]">Actions</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          {${modelPlural}.map((${modelNameLower}) => (
            <TableRow key={${modelNameLower}.id}>
${tableCells}
              <TableCell>
                <DropdownMenu>
                  <DropdownMenuTrigger asChild>
                    <Button
                      variant="ghost"
                      size="sm"
                      className="h-8 w-8 p-0"
                      disabled={deletingId === ${modelNameLower}.id}
                    >
                      <MoreHorizontal className="h-4 w-4" />
                      <span className="sr-only">Open menu</span>
                    </Button>
                  </DropdownMenuTrigger>
                  <DropdownMenuContent align="end">
                    <DropdownMenuItem onClick={() => handleEdit(${modelNameLower}.id)}>
                      <Pencil className="mr-2 h-4 w-4" />
                      Edit
                    </DropdownMenuItem>
                    <DropdownMenuItem
                      onClick={() => handleDelete(${modelNameLower}.id)}
                      className="text-destructive"
                    >
                      <Trash2 className="mr-2 h-4 w-4" />
                      Delete
                    </DropdownMenuItem>
                  </DropdownMenuContent>
                </DropdownMenu>
              </TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </div>
  );
}
`;
}

function generateTableCell(field: FieldInfo, modelNameLower: string): string {
  const fieldName = field.name;

  // Status badge
  if (fieldName === 'status') {
    return `              <TableCell>
                <span
                  className={\`inline-flex items-center rounded-full px-2 py-1 text-xs font-medium \${
                    ${modelNameLower}.${fieldName} === "${field.enumValues![0]}"
                      ? "bg-green-50 text-green-700 dark:bg-green-900/20 dark:text-green-400"
                      : "bg-gray-50 text-gray-700 dark:bg-gray-900/20 dark:text-gray-400"
                  }\`}
                >
                  {${modelNameLower}.${fieldName}}
                </span>
              </TableCell>`;
  }

  // Boolean field
  if (field.type === 'Boolean') {
    return `              <TableCell>
                {${modelNameLower}.${fieldName} ? "Yes" : "No"}
              </TableCell>`;
  }

  // DateTime field
  if (field.type === 'DateTime') {
    return `              <TableCell>
                {new Date(${modelNameLower}.${fieldName}).toLocaleDateString()}
              </TableCell>`;
  }

  // Decimal/Price field
  if (field.type === 'Decimal' && field.name.includes('price')) {
    return `              <TableCell>
                \${typeof ${modelNameLower}.${fieldName} === 'number'
                  ? ${modelNameLower}.${fieldName}.toFixed(2)
                  : parseFloat(${modelNameLower}.${fieldName} as any).toFixed(2)}
              </TableCell>`;
  }

  // Number field
  if (field.type === 'Int' || field.type === 'Decimal') {
    return `              <TableCell>
                {typeof ${modelNameLower}.${fieldName} === 'number'
                  ? ${modelNameLower}.${fieldName}
                  : ${modelNameLower}.${fieldName}}
              </TableCell>`;
  }

  // Default string field
  return `              <TableCell>{${modelNameLower}.${fieldName}}</TableCell>`;
}
